### ISSUE TITLE
Need persistent token to run node on homelab server

### ISSUE THREAD

**Issue by tonineri** [pi-node/pi-node#21]
So, I launched the pi-node app on my Docker Desktop (localhost), logged in and then it created a container.
I then stopped the container and moved the contents of `%appdata%/Pi Network/docker_volume` to my homelab server (ubuntu 24.04) which hosts some services through docker/portainer. Then I grabbed the necessary variables for the container (`POSTGRES_PASSWORD`, `NODE_PRIVATE_KEY`) and set them manually in the docker compose file (aka stack on portainer) and deployed the pi-node container like this:

```yaml
name: pi-network
services:
  testnet2:
    image: pinetwork/pi-node-docker:protocol19
    container_name: testnet2
    environment:
      - TZ=Europe/Rome
      - POSTGRES_PASSWORD=XXXXXXXXXXXX ## taken from %appdata%/Pi Network/docker_volume csv file
      - NODE_PRIVATE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ## taken from %appdata%/Pi Network/docker_volume csv file
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - STELLAR_CORE_VERSION=19.1.0-943.e801fd93b.focal
      - HORIZON_VERSION=2.18.1-284
    volumes:
      - /mnt/cache/appdata/pi-node/testnet_2/stellar:/opt/stellar ## migrated from %appdata%/Pi Network/docker_volume
      - /mnt/cache/appdata/pi-node/testnet_2/supervisor_logs:/var/log/supervisor ## migrated from %appdata%/Pi Network/docker_volume
      - /mnt/cache/appdata/pi-node/testnet_2/history:/history ## migrated from %appdata%/Pi Network/docker_volume
    ports:
      - 31401:8000
      - 31402:31402
      - 31403:1570
    labels:
      - "com.docker.compose.config-hash=2587661cb9641b6bdd89ed8cc196730bb343e7e510f4b027a2e186c591e084fe"
      - "com.docker.compose.container-number=1"
      - "com.docker.compose.oneoff=False"
      - "com.docker.compose.project=pi-network"
      - "com.docker.compose.service=testnet2"
      - "com.docker.compose.version=2.32.4"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "5"

    command: "--testnet2"
networks:
  host:
    external: true
```

What I need is to be able to create a persistent `NODE_PRIVATE_KEY` from the Pi app (assigning it a comment too) so that I can define it in my pi-node. I have 2 ubuntu servers running 24/7 and could be defined as "SuperNodes". I would dedicate 5 vCPUs from each of my servers to this. 
Is there any way one could be able to have a Pi Node section in their Pi app showing the nodes and their status based on their `NODE_PRIVATE_KEY`? I have no intention whatsoever to have Docker Desktop running on my Windows machine 24/7 as it's a PC and not a server.

Also, I'm in IT (Technical Architect) with vast experience on Docker and Kubernetes and strong skills on authentication protocols. Could make an OAuth based solution for this and tech documentation if necessary to be published on GitHub or DockerHub.
